server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/vitality
spring.datasource.username=postgres
spring.datasource.password=admin
twilo.account.sid=<value>
twilo.account.auth=<value>